backend:
  name: github
  repo: mishakessler/six-feet-over/code

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Post
    folder: content/posts
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: staff
    label: Staff Member
    folder: content/staff
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: name, label: Name }
      - { name: bio, label: Bio }
      - { name: body, label: Body, widget: markdown }
